export const KYNOVANT_PROFESSIONAL_PRICE = {
  planName: "Kynovant Professional",
  amount: "$99",
  period: "/month",
  trial: "14-day free trial",
} as const;

export const KYNOVANT_PUBLIC_CTA = {
  label: "Start 14-Day Free Trial",
  href: "/start-trial",
  note: "No payment required to create your coach account",
} as const;

export const KYNOVANT_FEATURE_GROUPS = [
  {
    eyebrow: "Program Operations",
    title: "Build, review, and assign training programs",
    summary:
      "Create reusable program templates and workout blueprints, organize them by goal and experience level, clone programs, assign them to clients, and keep active client programming connected to each client workspace.",
    proofPoints: [
      "Program templates with status, category, duration, recommended training days, search, filters, clone, edit, and delete controls.",
      "Workout blueprints for repeatable session structure.",
      "Client program assignment and portal delivery for the active plan.",
    ],
  },
  {
    eyebrow: "AI Assistance",
    title: "Generate a program draft for coach review",
    summary:
      "Kynovant AI starts from a coach-written brief, optional client context, and the reviewed Exercise Library. It drafts a program shell and weekly workouts in stages, then resolves exercises against the catalog and runs validation before the coach decides what to approve.",
    proofPoints: [
      "Brief inputs cover goal, weeks, days per week, split, experience level, equipment, session length, muscle priorities, limitations, restrictions, and allowed techniques.",
      "The model is given a bounded exercise candidate set and is instructed to use only catalog exercises.",
      "Drafts can be reviewed, edited, regenerated by day, discarded, or approved. Nothing becomes a real program without coach approval.",
    ],
  },
  {
    eyebrow: "Exercise Library",
    title: "Use a reviewed exercise catalog instead of free-text guessing",
    summary:
      "The library supports coach search, filtering, favorites, canonical platform exercises, coach-created exercises, alternate names, complete coaching cues, equipment, movement patterns, muscle roles, fatigue scores, joint stress, and exercise relationships.",
    proofPoints: [
      "Coaches can search and filter active exercises by status, muscle group, movement pattern, classification, difficulty, and scope.",
      "Exercise detail pages expose metadata, prescriptions, cues, substitutions, regressions, progressions, and related movements where available.",
      "The AI generator uses library candidates so warmups, cardio, mobility, and lifts resolve back to real catalog entries.",
    ],
  },
  {
    eyebrow: "Client Management",
    title: "Keep each client workspace tied to real coaching context",
    summary:
      "Coach HQ includes a client directory and client workspaces for profile context, goals, nutrition targets, sensitive notes, program timeline, check-ins, messages, and assigned work.",
    proofPoints: [
      "Clients are scoped to the coach relationship and shown in a coach-facing directory.",
      "Client workspaces collect program, goal, check-in, nutrition, and communication context in one place.",
      "Nutrition target management exists as targets and context, not automated nutrition diagnosis.",
    ],
  },
  {
    eyebrow: "Check-Ins",
    title: "Review weekly client check-ins without losing the thread",
    summary:
      "Clients submit weekly check-ins from the portal. Coaches get a review queue with waiting status, review states, client context, and notification events when new check-ins arrive.",
    proofPoints: [
      "Check-ins move through draft, submitted, in-review, and reviewed states.",
      "The queue prioritizes actionable submissions and shows waiting time.",
      "Client submissions create coach notifications.",
    ],
  },
  {
    eyebrow: "Messaging",
    title: "Handle coach-client messaging inside the workspace",
    summary:
      "Kynovant includes coach and client messaging surfaces with conversation lists, unread counts, thread views, and notifications when a client sends a new message.",
    proofPoints: [
      "Coach HQ lists conversations and opens dedicated message threads.",
      "The client portal includes its own messages page.",
      "Unread message badges refresh on a polling interval in the current MVP.",
    ],
  },
  {
    eyebrow: "Documents",
    title: "Share coaching documents through private storage",
    summary:
      "Coaches can upload documents, categorize them, share them with assigned clients, revoke access, archive records, and give clients short-lived signed links through the portal.",
    proofPoints: [
      "Supported files include PDF, images, Word, Excel, CSV, and text up to the configured size limit.",
      "Document assignments track required status, due dates, viewed state, revoked state, and assignment history.",
      "The storage bucket is private, and client downloads use expiring signed URLs after authorization.",
    ],
  },
  {
    eyebrow: "Schedule",
    title: "Plan appointments without claiming calendar sync",
    summary:
      "Coach HQ includes a schedule view for planning coach appointments with clients. The current production surface does not claim external calendar sync.",
    proofPoints: [
      "Coaches can plan appointments from the HQ schedule page.",
      "The public claim is intentionally limited to internal scheduling.",
      "External calendar synchronization is not described as shipped.",
    ],
  },
  {
    eyebrow: "Search And Notifications",
    title: "Find the work that needs attention",
    summary:
      "The HQ top bar includes authenticated search across clients, programs, and visible exercises, plus coach notifications for check-ins, messages, program generation, and billing events.",
    proofPoints: [
      "Search results link to clients, programs, and exercise details the coach is allowed to see.",
      "Notifications can be marked read individually or all at once.",
      "The Overview page surfaces real dashboard counts, waiting check-ins, active drafts, program templates, notifications, and upcoming appointments.",
    ],
  },
  {
    eyebrow: "Client Portal And Mobile",
    title: "Give clients a focused portal with PWA installation",
    summary:
      "Clients have a portal for their dashboard, active program, workout history, check-ins, messages, documents, nutrition targets, and progress context. The web app includes a manifest and icons for standalone PWA installation.",
    proofPoints: [
      "Portal routes exist for dashboard, program, progress, workout history, check-ins, messages, nutrition, and documents.",
      "The manifest defines standalone display, app icons, theme color, and mobile-friendly categories.",
      "This is a responsive web/PWA experience, not a native App Store or Play Store claim.",
    ],
  },
  {
    eyebrow: "Billing",
    title: "Sell one launch plan cleanly",
    summary:
      "Kynovant Professional is the launch plan at $99/month with a 14-day free trial. Stripe Checkout starts the subscription, and Coach HQ includes subscription management for active coaches.",
    proofPoints: [
      "Checkout creates a hosted Stripe subscription session with a 14-day trial.",
      "Billing status and Stripe portal access live inside Coach HQ for entitled coaches.",
      "Kynovant billing uses its own Stripe configuration, separate from legacy coaching-business billing.",
    ],
  },
] as const;

export const KYNOVANT_NOT_CLAIMED = [
  "Autonomous medical advice, diagnosis, treatment, or injury rehabilitation decisions.",
  "Autonomous nutrition prescribing beyond coach-managed nutrition targets and context.",
  "External calendar synchronization.",
  "Native iOS or Android app store apps.",
  "Fabricated performance statistics, coach earnings, client outcomes, or testimonials.",
  "Autonomous AI publication to clients without coach review and approval.",
] as const;
