// ─────────────────────────────────────────────────────────────
// Catalyst OS — Exercise Library Seed Data 008: Knee Flexion
// ─────────────────────────────────────────────────────────────

import type {
  EquipmentRequirement,
  ExerciseCueType,
  ExerciseDef,
  ExerciseRelationType,
  MuscleGroup,
  MuscleRole,
} from "./_shared";

export const KNEE_FLEXION_EXERCISE_SLUGS = [
  "seated-leg-curl",
  "lying-leg-curl",
  "nordic-curl",
] as const;

export const EXERCISES = [
  {
    slug: "seated-leg-curl",
    name: "Seated Leg Curl",
    movementPattern: "knee_flexion",
    classification: "isolation",
    resistanceType: "machine",
    difficulty: "beginner",
    defaultBodyPosition: "seated",
    fatigueCost: 4,
    technicalComplexity: 2,
    stabilityDemand: 1,
    jointStressHip: 1,
    jointStressKnee: 4,
    jointStressAnkle: 1,
    lengthenedBias: 8,
    shortenedBias: 6,
    stretchMediatedPotential: 8,
    defaultPrescription: {
      sets: 2,
      repsMin: 10,
      repsMax: 15,
      tempo: "3011",
      targetRpe: 7,
      restSeconds: 60,
      substitutionPolicy: "flexible",
    },
  },
  {
    slug: "lying-leg-curl",
    name: "Lying Leg Curl",
    movementPattern: "knee_flexion",
    classification: "isolation",
    resistanceType: "machine",
    difficulty: "beginner",
    defaultBodyPosition: "lying_prone",
    fatigueCost: 4,
    technicalComplexity: 2,
    stabilityDemand: 1,
    jointStressHip: 1,
    jointStressKnee: 4,
    jointStressAnkle: 1,
    lengthenedBias: 6,
    shortenedBias: 8,
    stretchMediatedPotential: 6,
    defaultPrescription: {
      sets: 2,
      repsMin: 10,
      repsMax: 15,
      tempo: "3011",
      targetRpe: 7,
      restSeconds: 60,
      substitutionPolicy: "flexible",
    },
  },
  {
    slug: "nordic-curl",
    name: "Nordic Curl",
    movementPattern: "knee_flexion",
    classification: "isolation",
    resistanceType: "bodyweight",
    difficulty: "advanced",
    defaultBodyPosition: "kneeling",
    fatigueCost: 6,
    technicalComplexity: 7,
    stabilityDemand: 5,
    jointStressHip: 2,
    jointStressKnee: 7,
    jointStressAnkle: 2,
    lengthenedBias: 10,
    shortenedBias: 2,
    stretchMediatedPotential: 10,
    defaultPrescription: {
      sets: 2,
      repsMin: 3,
      repsMax: 6,
      tempo: "5010",
      targetRpe: 8,
      restSeconds: 120,
      substitutionPolicy: "coach_review",
    },
  },
] as const satisfies readonly ExerciseDef[];

export const MUSCLES: Array<[string, MuscleGroup, MuscleRole]> = [
  ["seated-leg-curl", "hamstrings", "primary"],
  ["seated-leg-curl", "calves", "stabilizer"],

  ["lying-leg-curl", "hamstrings", "primary"],
  ["lying-leg-curl", "calves", "stabilizer"],
  ["lying-leg-curl", "glutes", "stabilizer"],

  ["nordic-curl", "hamstrings", "primary"],
  ["nordic-curl", "glutes", "secondary"],
  ["nordic-curl", "calves", "stabilizer"],
  ["nordic-curl", "spinal_erectors", "stabilizer"],
];

export const EXERCISE_EQUIPMENT: Array<[string, string, EquipmentRequirement]> = [
  ["seated-leg-curl", "seated-leg-curl-machine", "required"],
  ["lying-leg-curl", "lying-leg-curl-machine", "required"],
  ["nordic-curl", "glute-ham-developer", "required"],
];

export const CUES: Array<[string, ExerciseCueType, string, number]> = [
  ["seated-leg-curl", "setup",
    "Adjust the seat so the knee joint lines up with the machine pivot. Secure the thigh pad firmly and place the ankle pad just above the heels.",
    1],
  ["seated-leg-curl", "execution",
    "Curl the pad down by bending at the knees only, pause briefly in the shortened position, then return under control until the hamstrings are stretched without letting the hips lift.",
    2],
  ["seated-leg-curl", "common_error",
    "Letting the hips slide or the low back arch reduces hamstring tension and can irritate the knee. Keep the pelvis pinned to the seat throughout the rep.",
    3],
  ["seated-leg-curl", "safety",
    "Start with a conservative load after hamstring strains or posterior-knee irritation; avoid forcing the final degrees of knee flexion through pain.",
    4],

  ["lying-leg-curl", "setup",
    "Lie prone with the knees aligned to the machine pivot and the ankle pad resting just above the heels. Keep the hips heavy on the pad before the first rep.",
    1],
  ["lying-leg-curl", "execution",
    "Curl the heels toward the glutes without lifting the hips, pause briefly near the top, then lower slowly until the knees are nearly straight and the hamstrings stay loaded.",
    2],
  ["lying-leg-curl", "common_error",
    "Arching the low back or letting the hips pop up turns the rep into a hip-extension cheat. Reduce the load and keep the front of the hips pressed into the pad.",
    3],
  ["lying-leg-curl", "safety",
    "Use a smooth tempo and avoid bouncing out of the stretched bottom position, especially for clients with recent hamstring or posterior-knee symptoms.",
    4],

  ["nordic-curl", "setup",
    "Kneel on a padded surface with ankles secured under a GHD roller or held firmly by a partner. Keep the ribs down, glutes lightly squeezed, and body in one straight line from knees to shoulders.",
    1],
  ["nordic-curl", "execution",
    "Lower forward as slowly as possible by resisting knee extension with the hamstrings. Catch with the hands only when control is lost, then push lightly off the floor to return.",
    2],
  ["nordic-curl", "common_error",
    "Breaking at the hips shortens the lever and removes the eccentric hamstring demand. Keep the hips extended and move as one long segment from the knees.",
    3],
  ["nordic-curl", "safety",
    "Treat this as a high-tension eccentric exercise: use low volume, stop well before cramping or sharp pain, and regress to assisted reps when control is limited.",
    4],
];

export const RELATIONS: Array<[string, string, ExerciseRelationType, string]> = [
  ["seated-leg-curl", "lying-leg-curl", "substitute",
    "Both are machine-guided knee-flexion isolations with similar hamstring stimulus; choose based on machine availability and client comfort."],
  ["lying-leg-curl", "seated-leg-curl", "substitute",
    "Both are machine-guided knee-flexion isolations with similar hamstring stimulus; seated setup may be preferable when prone positioning is uncomfortable."],
  ["lying-leg-curl", "nordic-curl", "regression",
    "Lying leg curl is the lower-skill, lower-tension regression before progressing to high-load eccentric bodyweight knee flexion."],
  ["nordic-curl", "lying-leg-curl", "progression",
    "Nordic curl is a progression from machine knee flexion because it adds high eccentric demand, longer lever mechanics, and greater tissue-loading risk."],
  ["seated-leg-curl", "nordic-curl", "regression",
    "Seated leg curl builds direct hamstring capacity with lower technical and tissue stress before Nordic curl exposure."],
  ["nordic-curl", "seated-leg-curl", "progression",
    "Nordic curl is a progression from seated leg curl for athletes ready for aggressive lengthened-position eccentric hamstring loading."],
  ["lying-leg-curl", "nordic-curl", "lower_joint_stress",
    "The machine curl provides controllable loading and avoids the high eccentric knee-flexion torque of Nordic curls."],
  ["nordic-curl", "lying-leg-curl", "higher_joint_stress",
    "Nordic curls impose substantially higher eccentric hamstring and posterior-knee stress than a machine lying leg curl."],
];
