// ─────────────────────────────────────────────────────────────
// Catalyst OS — Exercise Library Seed Data 009: Launch Families
// ─────────────────────────────────────────────────────────────

import type {
  EquipmentRequirement,
  ExerciseCueType,
  ExerciseDef,
  ExerciseRelationType,
  MuscleGroup,
  MuscleRole,
} from "./_shared";

export const LOCAL_EQUIPMENT = [
  { slug: "elliptical", name: "Elliptical Trainer", category: "cardio_equipment" },
  { slug: "recumbent-bike", name: "Recumbent Bike", category: "cardio_equipment" },
  { slug: "foam-roller", name: "Foam Roller", category: "accessories" },
] as const;

export const CALF_EXERCISE_SLUGS = [
  "standing-calf-raise-machine",
  "seated-calf-raise",
  "leg-press-calf-raise",
  "bodyweight-standing-calf-raise",
  "single-leg-standing-calf-raise",
  "dumbbell-standing-calf-raise",
] as const;

export const CARDIO_EXERCISE_SLUGS = [
  "treadmill-walk",
  "treadmill-run",
  "incline-treadmill-walk",
  "stationary-bike",
  "recumbent-bike",
  "elliptical",
  "rowing-machine",
  "stair-climber",
] as const;

export const MOBILITY_EXERCISE_SLUGS = [
  "band-shoulder-external-rotation-mobility",
  "wall-slide",
  "thoracic-extension-on-foam-roller",
  "open-book-thoracic-rotation",
  "half-kneeling-hip-flexor-mobilization",
  "ninety-ninety-hip-switch",
  "ankle-dorsiflexion-rock",
  "deep-squat-pry",
] as const;

const calfPrescription = {
  sets: 3,
  repsMin: 10,
  repsMax: 20,
  tempo: "2111",
  targetRpe: 7,
  restSeconds: 60,
  substitutionPolicy: "flexible",
};

const steadyCardioPrescription = {
  sets: 1,
  durationSeconds: 1200,
  targetRpeMin: 3,
  targetRpeMax: 6,
  restSeconds: 0,
  substitutionPolicy: "flexible",
};

const mobilityPrescription = {
  sets: 1,
  durationSeconds: 60,
  repsMin: 6,
  repsMax: 10,
  targetRpe: 3,
  restSeconds: 15,
  substitutionPolicy: "flexible",
};

export const EXERCISES = [
  {
    slug: "standing-calf-raise-machine",
    name: "Standing Calf Raise Machine",
    movementPattern: "gait",
    classification: "isolation",
    resistanceType: "machine",
    difficulty: "beginner",
    defaultBodyPosition: "standing",
    fatigueCost: 3,
    technicalComplexity: 2,
    stabilityDemand: 2,
    jointStressSpine: 2,
    jointStressHip: 1,
    jointStressKnee: 2,
    jointStressAnkle: 5,
    lengthenedBias: 6,
    shortenedBias: 8,
    stretchMediatedPotential: 5,
    defaultPrescription: calfPrescription,
  },
  {
    slug: "seated-calf-raise",
    name: "Seated Calf Raise",
    movementPattern: "gait",
    classification: "isolation",
    resistanceType: "machine",
    difficulty: "beginner",
    defaultBodyPosition: "seated",
    fatigueCost: 3,
    technicalComplexity: 1,
    stabilityDemand: 1,
    jointStressHip: 1,
    jointStressKnee: 2,
    jointStressAnkle: 4,
    lengthenedBias: 5,
    shortenedBias: 8,
    stretchMediatedPotential: 4,
    defaultPrescription: calfPrescription,
  },
  {
    slug: "leg-press-calf-raise",
    name: "Leg Press Calf Raise",
    movementPattern: "gait",
    classification: "isolation",
    resistanceType: "machine",
    difficulty: "beginner",
    defaultBodyPosition: "seated",
    fatigueCost: 3,
    technicalComplexity: 2,
    stabilityDemand: 1,
    jointStressSpine: 1,
    jointStressHip: 1,
    jointStressKnee: 2,
    jointStressAnkle: 5,
    lengthenedBias: 6,
    shortenedBias: 8,
    stretchMediatedPotential: 5,
    defaultPrescription: calfPrescription,
  },
  {
    slug: "bodyweight-standing-calf-raise",
    name: "Bodyweight Standing Calf Raise",
    movementPattern: "gait",
    classification: "isolation",
    resistanceType: "bodyweight",
    difficulty: "beginner",
    defaultBodyPosition: "standing",
    fatigueCost: 2,
    technicalComplexity: 1,
    stabilityDemand: 2,
    jointStressKnee: 1,
    jointStressAnkle: 3,
    lengthenedBias: 5,
    shortenedBias: 7,
    stretchMediatedPotential: 3,
    defaultPrescription: { ...calfPrescription, sets: 2, repsMin: 12, repsMax: 25 },
  },
  {
    slug: "single-leg-standing-calf-raise",
    name: "Single-Leg Standing Calf Raise",
    movementPattern: "gait",
    classification: "isolation",
    resistanceType: "bodyweight",
    difficulty: "intermediate",
    unilateral: true,
    defaultBodyPosition: "standing",
    fatigueCost: 3,
    technicalComplexity: 3,
    stabilityDemand: 5,
    jointStressHip: 1,
    jointStressKnee: 2,
    jointStressAnkle: 5,
    lengthenedBias: 6,
    shortenedBias: 8,
    stretchMediatedPotential: 5,
    defaultPrescription: { ...calfPrescription, sets: 2, repsMin: 8, repsMax: 15 },
  },
  {
    slug: "dumbbell-standing-calf-raise",
    name: "Dumbbell Standing Calf Raise",
    movementPattern: "gait",
    classification: "isolation",
    resistanceType: "dumbbell",
    difficulty: "beginner",
    defaultBodyPosition: "standing",
    fatigueCost: 3,
    technicalComplexity: 2,
    stabilityDemand: 3,
    jointStressSpine: 1,
    jointStressHip: 1,
    jointStressKnee: 2,
    jointStressAnkle: 5,
    lengthenedBias: 6,
    shortenedBias: 8,
    stretchMediatedPotential: 5,
    defaultPrescription: calfPrescription,
  },
  {
    slug: "treadmill-walk",
    name: "Treadmill Walk",
    movementPattern: "gait",
    classification: "cardio",
    resistanceType: "machine",
    difficulty: "beginner",
    isTimeBased: true,
    isDistanceBased: true,
    isCardio: true,
    defaultBodyPosition: "standing",
    fatigueCost: 2,
    technicalComplexity: 1,
    stabilityDemand: 2,
    jointStressHip: 2,
    jointStressKnee: 2,
    jointStressAnkle: 2,
    lengthenedBias: 0,
    shortenedBias: 0,
    stretchMediatedPotential: 0,
    defaultPrescription: steadyCardioPrescription,
  },
  {
    slug: "treadmill-run",
    name: "Treadmill Run",
    movementPattern: "gait",
    classification: "cardio",
    resistanceType: "machine",
    difficulty: "intermediate",
    isTimeBased: true,
    isDistanceBased: true,
    isCardio: true,
    defaultBodyPosition: "standing",
    fatigueCost: 5,
    technicalComplexity: 2,
    stabilityDemand: 3,
    jointStressHip: 4,
    jointStressKnee: 5,
    jointStressAnkle: 5,
    lengthenedBias: 0,
    shortenedBias: 0,
    stretchMediatedPotential: 0,
    defaultPrescription: { ...steadyCardioPrescription, durationSeconds: 900, targetRpeMin: 5, targetRpeMax: 8 },
  },
  {
    slug: "incline-treadmill-walk",
    name: "Incline Treadmill Walk",
    movementPattern: "gait",
    classification: "cardio",
    resistanceType: "machine",
    difficulty: "beginner",
    isTimeBased: true,
    isDistanceBased: true,
    isCardio: true,
    defaultBodyPosition: "standing",
    fatigueCost: 4,
    technicalComplexity: 1,
    stabilityDemand: 2,
    jointStressHip: 3,
    jointStressKnee: 3,
    jointStressAnkle: 4,
    lengthenedBias: 0,
    shortenedBias: 0,
    stretchMediatedPotential: 0,
    defaultPrescription: { ...steadyCardioPrescription, durationSeconds: 900, targetRpeMin: 4, targetRpeMax: 7 },
  },
  {
    slug: "stationary-bike",
    name: "Stationary Bike",
    movementPattern: "gait",
    classification: "cardio",
    resistanceType: "machine",
    difficulty: "beginner",
    isTimeBased: true,
    isDistanceBased: true,
    isCardio: true,
    defaultBodyPosition: "seated",
    fatigueCost: 3,
    technicalComplexity: 1,
    stabilityDemand: 1,
    jointStressSpine: 1,
    jointStressHip: 2,
    jointStressKnee: 2,
    jointStressAnkle: 1,
    lengthenedBias: 0,
    shortenedBias: 0,
    stretchMediatedPotential: 0,
    defaultPrescription: steadyCardioPrescription,
  },
  {
    slug: "recumbent-bike",
    name: "Recumbent Bike",
    movementPattern: "gait",
    classification: "cardio",
    resistanceType: "machine",
    difficulty: "beginner",
    isTimeBased: true,
    isDistanceBased: true,
    isCardio: true,
    defaultBodyPosition: "seated",
    fatigueCost: 2,
    technicalComplexity: 1,
    stabilityDemand: 1,
    jointStressSpine: 1,
    jointStressHip: 1,
    jointStressKnee: 2,
    jointStressAnkle: 1,
    lengthenedBias: 0,
    shortenedBias: 0,
    stretchMediatedPotential: 0,
    defaultPrescription: { ...steadyCardioPrescription, targetRpeMin: 2, targetRpeMax: 5 },
  },
  {
    slug: "elliptical",
    name: "Elliptical",
    movementPattern: "gait",
    classification: "cardio",
    resistanceType: "machine",
    difficulty: "beginner",
    isTimeBased: true,
    isDistanceBased: true,
    isCardio: true,
    defaultBodyPosition: "standing",
    fatigueCost: 3,
    technicalComplexity: 1,
    stabilityDemand: 2,
    jointStressHip: 2,
    jointStressKnee: 2,
    jointStressAnkle: 2,
    lengthenedBias: 0,
    shortenedBias: 0,
    stretchMediatedPotential: 0,
    defaultPrescription: steadyCardioPrescription,
  },
  {
    slug: "rowing-machine",
    name: "Rowing Machine",
    movementPattern: "gait",
    classification: "cardio",
    resistanceType: "machine",
    difficulty: "beginner",
    isTimeBased: true,
    isDistanceBased: true,
    isCardio: true,
    defaultBodyPosition: "seated",
    fatigueCost: 4,
    technicalComplexity: 3,
    stabilityDemand: 3,
    jointStressShoulder: 2,
    jointStressElbow: 2,
    jointStressSpine: 3,
    jointStressHip: 3,
    jointStressKnee: 3,
    jointStressAnkle: 2,
    lengthenedBias: 0,
    shortenedBias: 0,
    stretchMediatedPotential: 0,
    defaultPrescription: { ...steadyCardioPrescription, durationSeconds: 900, targetRpeMin: 4, targetRpeMax: 7 },
  },
  {
    slug: "stair-climber",
    name: "Stair Climber",
    movementPattern: "gait",
    classification: "cardio",
    resistanceType: "machine",
    difficulty: "beginner",
    isTimeBased: true,
    isDistanceBased: true,
    isCardio: true,
    defaultBodyPosition: "standing",
    fatigueCost: 4,
    technicalComplexity: 1,
    stabilityDemand: 2,
    jointStressHip: 3,
    jointStressKnee: 3,
    jointStressAnkle: 3,
    lengthenedBias: 0,
    shortenedBias: 0,
    stretchMediatedPotential: 0,
    defaultPrescription: { ...steadyCardioPrescription, durationSeconds: 900, targetRpeMin: 4, targetRpeMax: 7 },
  },
  {
    slug: "band-shoulder-external-rotation-mobility",
    name: "Band Shoulder External Rotation Mobility",
    movementPattern: "external_rotation",
    classification: "mobility",
    resistanceType: "band",
    difficulty: "beginner",
    isMobility: true,
    defaultBodyPosition: "standing",
    fatigueCost: 1,
    technicalComplexity: 2,
    stabilityDemand: 2,
    jointStressShoulder: 2,
    jointStressElbow: 1,
    jointStressWrist: 1,
    lengthenedBias: 0,
    shortenedBias: 0,
    stretchMediatedPotential: 0,
    defaultPrescription: mobilityPrescription,
  },
  {
    slug: "wall-slide",
    name: "Wall Slide",
    movementPattern: "scapular_retraction",
    classification: "mobility",
    resistanceType: "bodyweight",
    difficulty: "beginner",
    isMobility: true,
    defaultBodyPosition: "standing",
    fatigueCost: 1,
    technicalComplexity: 2,
    stabilityDemand: 2,
    jointStressShoulder: 2,
    jointStressSpine: 1,
    lengthenedBias: 0,
    shortenedBias: 0,
    stretchMediatedPotential: 0,
    defaultPrescription: mobilityPrescription,
  },
  {
    slug: "thoracic-extension-on-foam-roller",
    name: "Thoracic Extension on Foam Roller",
    movementPattern: "rotation",
    classification: "mobility",
    resistanceType: "bodyweight",
    difficulty: "beginner",
    isMobility: true,
    defaultBodyPosition: "lying_supine",
    fatigueCost: 1,
    technicalComplexity: 1,
    stabilityDemand: 1,
    jointStressShoulder: 1,
    jointStressSpine: 2,
    lengthenedBias: 0,
    shortenedBias: 0,
    stretchMediatedPotential: 0,
    defaultPrescription: mobilityPrescription,
  },
  {
    slug: "open-book-thoracic-rotation",
    name: "Open Book Thoracic Rotation",
    movementPattern: "rotation",
    classification: "mobility",
    resistanceType: "bodyweight",
    difficulty: "beginner",
    isMobility: true,
    defaultBodyPosition: "lying_supine",
    fatigueCost: 1,
    technicalComplexity: 1,
    stabilityDemand: 1,
    jointStressShoulder: 1,
    jointStressSpine: 2,
    jointStressHip: 1,
    lengthenedBias: 0,
    shortenedBias: 0,
    stretchMediatedPotential: 0,
    defaultPrescription: mobilityPrescription,
  },
  {
    slug: "half-kneeling-hip-flexor-mobilization",
    name: "Half-Kneeling Hip Flexor Mobilization",
    movementPattern: "hip_flexion",
    classification: "mobility",
    resistanceType: "bodyweight",
    difficulty: "beginner",
    isMobility: true,
    defaultBodyPosition: "kneeling",
    fatigueCost: 1,
    technicalComplexity: 2,
    stabilityDemand: 2,
    jointStressSpine: 1,
    jointStressHip: 2,
    jointStressKnee: 2,
    lengthenedBias: 0,
    shortenedBias: 0,
    stretchMediatedPotential: 0,
    defaultPrescription: mobilityPrescription,
  },
  {
    slug: "ninety-ninety-hip-switch",
    name: "90/90 Hip Switch",
    movementPattern: "hip_flexion",
    classification: "mobility",
    resistanceType: "bodyweight",
    difficulty: "beginner",
    isMobility: true,
    defaultBodyPosition: "seated",
    fatigueCost: 1,
    technicalComplexity: 2,
    stabilityDemand: 2,
    jointStressSpine: 1,
    jointStressHip: 3,
    jointStressKnee: 2,
    lengthenedBias: 0,
    shortenedBias: 0,
    stretchMediatedPotential: 0,
    defaultPrescription: mobilityPrescription,
  },
  {
    slug: "ankle-dorsiflexion-rock",
    name: "Ankle Dorsiflexion Rock",
    movementPattern: "gait",
    classification: "mobility",
    resistanceType: "bodyweight",
    difficulty: "beginner",
    isMobility: true,
    defaultBodyPosition: "split_stance",
    fatigueCost: 1,
    technicalComplexity: 1,
    stabilityDemand: 2,
    jointStressKnee: 2,
    jointStressAnkle: 2,
    lengthenedBias: 0,
    shortenedBias: 0,
    stretchMediatedPotential: 0,
    defaultPrescription: mobilityPrescription,
  },
  {
    slug: "deep-squat-pry",
    name: "Deep Squat Pry",
    movementPattern: "squat_bilateral",
    classification: "mobility",
    resistanceType: "bodyweight",
    difficulty: "beginner",
    isMobility: true,
    defaultBodyPosition: "standing",
    fatigueCost: 2,
    technicalComplexity: 2,
    stabilityDemand: 3,
    jointStressSpine: 2,
    jointStressHip: 3,
    jointStressKnee: 3,
    jointStressAnkle: 3,
    lengthenedBias: 0,
    shortenedBias: 0,
    stretchMediatedPotential: 0,
    defaultPrescription: { ...mobilityPrescription, durationSeconds: 45 },
  },
] as const satisfies readonly ExerciseDef[];

export const MUSCLES: Array<[string, MuscleGroup, MuscleRole]> = [
  ["standing-calf-raise-machine", "calves", "primary"],
  ["standing-calf-raise-machine", "tibialis", "stabilizer"],
  ["standing-calf-raise-machine", "glutes", "stabilizer"],
  ["seated-calf-raise", "calves", "primary"],
  ["seated-calf-raise", "tibialis", "stabilizer"],
  ["leg-press-calf-raise", "calves", "primary"],
  ["leg-press-calf-raise", "tibialis", "stabilizer"],
  ["bodyweight-standing-calf-raise", "calves", "primary"],
  ["bodyweight-standing-calf-raise", "tibialis", "stabilizer"],
  ["single-leg-standing-calf-raise", "calves", "primary"],
  ["single-leg-standing-calf-raise", "tibialis", "stabilizer"],
  ["single-leg-standing-calf-raise", "glutes", "stabilizer"],
  ["dumbbell-standing-calf-raise", "calves", "primary"],
  ["dumbbell-standing-calf-raise", "tibialis", "stabilizer"],
  ["dumbbell-standing-calf-raise", "forearms", "stabilizer"],

  ["treadmill-walk", "cardiovascular", "primary"],
  ["treadmill-walk", "calves", "secondary"],
  ["treadmill-walk", "glutes", "secondary"],
  ["treadmill-run", "cardiovascular", "primary"],
  ["treadmill-run", "calves", "secondary"],
  ["treadmill-run", "quadriceps", "secondary"],
  ["treadmill-run", "glutes", "secondary"],
  ["incline-treadmill-walk", "cardiovascular", "primary"],
  ["incline-treadmill-walk", "calves", "secondary"],
  ["incline-treadmill-walk", "glutes", "secondary"],
  ["stationary-bike", "cardiovascular", "primary"],
  ["stationary-bike", "quadriceps", "secondary"],
  ["stationary-bike", "glutes", "secondary"],
  ["recumbent-bike", "cardiovascular", "primary"],
  ["recumbent-bike", "quadriceps", "secondary"],
  ["elliptical", "cardiovascular", "primary"],
  ["elliptical", "glutes", "secondary"],
  ["elliptical", "calves", "secondary"],
  ["rowing-machine", "cardiovascular", "primary"],
  ["rowing-machine", "quadriceps", "secondary"],
  ["rowing-machine", "hamstrings", "secondary"],
  ["rowing-machine", "upper_back", "secondary"],
  ["rowing-machine", "spinal_erectors", "stabilizer"],
  ["stair-climber", "cardiovascular", "primary"],
  ["stair-climber", "quadriceps", "secondary"],
  ["stair-climber", "glutes", "secondary"],
  ["stair-climber", "calves", "secondary"],

  ["band-shoulder-external-rotation-mobility", "rear_deltoid", "primary"],
  ["band-shoulder-external-rotation-mobility", "trapezius", "stabilizer"],
  ["wall-slide", "upper_back", "primary"],
  ["wall-slide", "rear_deltoid", "secondary"],
  ["thoracic-extension-on-foam-roller", "spinal_erectors", "primary"],
  ["thoracic-extension-on-foam-roller", "rectus_abdominis", "stabilizer"],
  ["open-book-thoracic-rotation", "obliques", "primary"],
  ["open-book-thoracic-rotation", "spinal_erectors", "secondary"],
  ["half-kneeling-hip-flexor-mobilization", "hip_flexors", "primary"],
  ["half-kneeling-hip-flexor-mobilization", "glutes", "stabilizer"],
  ["ninety-ninety-hip-switch", "hip_flexors", "primary"],
  ["ninety-ninety-hip-switch", "glutes", "secondary"],
  ["ankle-dorsiflexion-rock", "calves", "primary"],
  ["ankle-dorsiflexion-rock", "tibialis", "secondary"],
  ["deep-squat-pry", "adductors", "primary"],
  ["deep-squat-pry", "calves", "secondary"],
  ["deep-squat-pry", "glutes", "secondary"],
];

export const EXERCISE_EQUIPMENT: Array<[string, string, EquipmentRequirement]> = [
  ["standing-calf-raise-machine", "machine-calf-raise", "required"],
  ["seated-calf-raise", "seated-calf-raise-machine", "required"],
  ["leg-press-calf-raise", "leg-press-machine", "required"],
  ["dumbbell-standing-calf-raise", "dumbbells", "required"],
  ["treadmill-walk", "treadmill", "required"],
  ["treadmill-run", "treadmill", "required"],
  ["incline-treadmill-walk", "treadmill", "required"],
  ["stationary-bike", "stationary-bike", "required"],
  ["recumbent-bike", "recumbent-bike", "required"],
  ["elliptical", "elliptical", "required"],
  ["rowing-machine", "rowing-machine", "required"],
  ["stair-climber", "stair-climber", "required"],
  ["band-shoulder-external-rotation-mobility", "resistance-band", "required"],
  ["thoracic-extension-on-foam-roller", "foam-roller", "required"],
];

export const CUES: Array<[string, ExerciseCueType, string, number]> = [
  ["standing-calf-raise-machine", "setup", "Set the shoulder pads so you can stand tall with the balls of the feet on the platform edge and heels free to move. Keep knees softly unlocked.", 1],
  ["standing-calf-raise-machine", "execution", "Lower the heels under control until the calves stretch, then drive through the big-toe side of the foot to rise as high as possible. Pause briefly at the top.", 2],
  ["standing-calf-raise-machine", "common_error", "Bouncing through the bottom uses tendon recoil instead of calf tension. Slow the descent and pause before each raise.", 3],
  ["standing-calf-raise-machine", "safety", "Avoid rolling onto the outside edges of the feet; keep pressure even through the forefoot to reduce ankle irritation.", 4],
  ["seated-calf-raise", "setup", "Sit with the knees under the pad and the balls of the feet on the platform edge. Secure the thigh pad without pinching the knees.", 1],
  ["seated-calf-raise", "execution", "Let the heels sink until the calves stretch, then raise the heels as high as possible while keeping the knees pointed forward.", 2],
  ["seated-calf-raise", "common_error", "Cutting the bottom range short removes the most useful loaded stretch. Use a load that allows a controlled full range.", 3],
  ["seated-calf-raise", "safety", "Do not force the knee pad down onto painful knees; adjust pad height or choose a standing variation if pressure is uncomfortable.", 4],
  ["leg-press-calf-raise", "setup", "Sit in the leg press with the balls of the feet low on the platform and knees nearly straight but not locked. Keep the safety stops set.", 1],
  ["leg-press-calf-raise", "execution", "Move only at the ankles: lower the sled by letting the heels drop, then press through the forefoot to plantarflex fully.", 2],
  ["leg-press-calf-raise", "common_error", "Letting the knees bend turns the drill into a small leg press. Keep knee angle fixed and reduce load if needed.", 3],
  ["leg-press-calf-raise", "safety", "Keep the feet securely on the platform and never chase extra range if the forefoot starts to slip.", 4],
  ["bodyweight-standing-calf-raise", "setup", "Stand tall near a stable support with feet hip-width and toes pointing forward. Use the support only for balance.", 1],
  ["bodyweight-standing-calf-raise", "execution", "Rise onto the balls of the feet, pause, then lower slowly until the heels lightly touch down or move below the step if using one.", 2],
  ["bodyweight-standing-calf-raise", "common_error", "Rocking the hips forward creates momentum and hides weak calf control. Keep the ribs stacked over the pelvis.", 3],
  ["bodyweight-standing-calf-raise", "safety", "Use a flat floor before progressing to a step if balance or Achilles comfort is uncertain.", 4],
  ["single-leg-standing-calf-raise", "setup", "Stand on one foot near a support, keeping the working knee softly unlocked and the pelvis level.", 1],
  ["single-leg-standing-calf-raise", "execution", "Lower the heel under control, then raise as high as possible without twisting the ankle or pushing heavily through the hands.", 2],
  ["single-leg-standing-calf-raise", "common_error", "Letting the ankle collapse inward shifts stress away from the calf and can irritate the joint. Keep the heel tracking straight.", 3],
  ["single-leg-standing-calf-raise", "safety", "Regress to two legs if the working ankle cannot stay stable through the full range.", 4],
  ["dumbbell-standing-calf-raise", "setup", "Hold dumbbells at the sides and stand tall with the balls of the feet grounded or on a stable edge.", 1],
  ["dumbbell-standing-calf-raise", "execution", "Raise the heels smoothly, pause at peak contraction, then lower slowly into a controlled stretch without leaning forward.", 2],
  ["dumbbell-standing-calf-raise", "common_error", "Shrugging or swinging the dumbbells adds noise without improving calf loading. Keep the arms quiet.", 3],
  ["dumbbell-standing-calf-raise", "safety", "Choose a load that does not pull balance forward; use a machine variation when grip or balance limits calf work.", 4],

  ["treadmill-walk", "setup", "Set speed to a pace that allows relaxed posture and quiet foot strikes. Stand centered on the belt before starting.", 1],
  ["treadmill-walk", "execution", "Walk with tall posture, natural arm swing, and consistent breathing. Adjust speed to stay in the intended effort zone.", 2],
  ["treadmill-walk", "common_error", "Holding the rails heavily reduces gait demand and changes posture. Lower speed instead of leaning on the handles.", 3],
  ["treadmill-walk", "safety", "Use the safety clip when balance is uncertain and step off only after the belt slows.", 4],
  ["treadmill-run", "setup", "Start with a warm-up walk or jog before increasing speed. Keep enough belt room behind and ahead to run naturally.", 1],
  ["treadmill-run", "execution", "Run with quick, quiet steps and a slight forward lean from the ankles. Keep effort matched to the planned duration or interval.", 2],
  ["treadmill-run", "common_error", "Overstriding with loud heel strikes raises joint stress and wastes energy. Shorten stride and increase cadence slightly.", 3],
  ["treadmill-run", "safety", "Stop or regress to walking if pain, dizziness, or uncontrolled belt drift appears.", 4],
  ["incline-treadmill-walk", "setup", "Set a modest incline and walking speed before starting. Stand tall rather than hanging from the rails.", 1],
  ["incline-treadmill-walk", "execution", "Drive each step through the whole foot while keeping the torso upright and breathing steady.", 2],
  ["incline-treadmill-walk", "common_error", "Leaning back on locked arms cancels much of the incline demand. Reduce incline or speed to maintain posture.", 3],
  ["incline-treadmill-walk", "safety", "Use conservative inclines for clients with Achilles, calf, or low-back sensitivity.", 4],
  ["stationary-bike", "setup", "Adjust seat height so the knee is slightly bent at the bottom of the pedal stroke. Set handlebars where the back can stay comfortable.", 1],
  ["stationary-bike", "execution", "Pedal smoothly with even pressure through the full circle and adjust resistance to the prescribed effort.", 2],
  ["stationary-bike", "common_error", "A seat set too low overloads the knees and shortens the stroke. Raise it until the hips stay level while pedaling.", 3],
  ["stationary-bike", "safety", "Keep resistance low enough that cadence stays controlled without knee pain or hip rocking.", 4],
  ["recumbent-bike", "setup", "Adjust the seat so the knees remain slightly bent at full reach and the back rests comfortably against the pad.", 1],
  ["recumbent-bike", "execution", "Pedal with steady cadence and smooth pressure, keeping the pelvis settled against the seat back.", 2],
  ["recumbent-bike", "common_error", "Scooting forward removes back support and can crowd the hips. Reset the seat position before adding resistance.", 3],
  ["recumbent-bike", "safety", "Use this option when upright balance or spinal loading needs to be minimized, but stop if knee discomfort builds.", 4],
  ["elliptical", "setup", "Step onto the pedals carefully, hold the handles, and choose a resistance that allows smooth continuous motion.", 1],
  ["elliptical", "execution", "Move through a steady stride without bouncing, keeping the torso tall and pressure even through both feet.", 2],
  ["elliptical", "common_error", "Letting the machine carry the legs reduces effort and control. Keep active pressure through the pedals.", 3],
  ["elliptical", "safety", "Start and stop gradually; wait for the pedals to settle before stepping off.", 4],
  ["rowing-machine", "setup", "Set the foot straps across the widest part of the feet and begin with shins near vertical, arms long, and spine tall.", 1],
  ["rowing-machine", "execution", "Drive with the legs first, then swing the torso slightly back and finish by pulling the handle to the lower ribs. Reverse in the same controlled order.", 2],
  ["rowing-machine", "common_error", "Pulling early with the arms turns the stroke into a weak row and can irritate the back. Let the legs initiate each drive.", 3],
  ["rowing-machine", "safety", "Keep the spine neutral and resistance moderate until stroke sequencing is consistent.", 4],
  ["stair-climber", "setup", "Start at a low step rate with both hands lightly touching the rails for balance only.", 1],
  ["stair-climber", "execution", "Step through the whole foot, stand tall, and keep cadence steady without skipping steps.", 2],
  ["stair-climber", "common_error", "Leaning heavily on the rails unloads the legs and can round the back. Lower the speed and stay upright.", 3],
  ["stair-climber", "safety", "Step off only after the machine slows and avoid high step rates for clients with uncontrolled knee pain.", 4],

  ["band-shoulder-external-rotation-mobility", "setup", "Anchor a light band at elbow height and stand side-on with the elbow bent to 90 degrees and tucked near the ribs.", 1],
  ["band-shoulder-external-rotation-mobility", "execution", "Rotate the forearm away from the body slowly while the elbow stays still, then return with control.", 2],
  ["band-shoulder-external-rotation-mobility", "common_error", "Letting the elbow drift behind the body turns the drill into a shoulder extension pattern. Keep the upper arm quiet.", 3],
  ["band-shoulder-external-rotation-mobility", "safety", "Use very light tension and stay pain-free; this is preparation, not a max-effort strength set.", 4],
  ["wall-slide", "setup", "Stand with back against a wall, ribs down, and forearms touching the wall as much as comfortable.", 1],
  ["wall-slide", "execution", "Slide the arms upward while keeping the ribs from flaring, then return to the start under control.", 2],
  ["wall-slide", "common_error", "Arching the low back creates false overhead range. Exhale, brace lightly, and use only the range you can own.", 3],
  ["wall-slide", "safety", "Stop short of pinching or numbness in the shoulder or arm.", 4],
  ["thoracic-extension-on-foam-roller", "setup", "Lie on your back with a foam roller across the upper back and hands supporting the head.", 1],
  ["thoracic-extension-on-foam-roller", "execution", "Gently extend over the roller while keeping the ribs from flaring, then move the roller one segment and repeat.", 2],
  ["thoracic-extension-on-foam-roller", "common_error", "Cranking the neck or low back creates motion in the wrong place. Keep the neck supported and focus on the upper back.", 3],
  ["thoracic-extension-on-foam-roller", "safety", "Avoid aggressive pressure on the neck or low back and skip loaded extension if symptoms increase.", 4],
  ["open-book-thoracic-rotation", "setup", "Lie on one side with knees bent and stacked, arms straight in front of the chest.", 1],
  ["open-book-thoracic-rotation", "execution", "Rotate the top arm and chest open toward the floor behind you while the knees stay stacked, then return slowly.", 2],
  ["open-book-thoracic-rotation", "common_error", "Letting the top knee roll back turns the drill into hip rotation. Keep the legs pinned and rotate through the upper back.", 3],
  ["open-book-thoracic-rotation", "safety", "Move through comfortable range only and avoid forcing the shoulder toward the floor.", 4],
  ["half-kneeling-hip-flexor-mobilization", "setup", "Kneel with one foot forward and the back knee padded. Tuck the pelvis slightly and squeeze the back-side glute.", 1],
  ["half-kneeling-hip-flexor-mobilization", "execution", "Shift the hips forward a few inches while keeping the ribs stacked, then return and repeat with small controlled pulses.", 2],
  ["half-kneeling-hip-flexor-mobilization", "common_error", "Arching the low back fakes hip extension and misses the hip flexors. Keep the pelvis tucked before moving.", 3],
  ["half-kneeling-hip-flexor-mobilization", "safety", "Pad the knee and keep pressure gentle if kneeling irritates the front of the knee.", 4],
  ["ninety-ninety-hip-switch", "setup", "Sit with both knees bent near 90 degrees, one leg in front and one to the side, hands available for support.", 1],
  ["ninety-ninety-hip-switch", "execution", "Rotate both knees from side to side under control while keeping the torso tall and hips grounded as much as possible.", 2],
  ["ninety-ninety-hip-switch", "common_error", "Collapsing backward removes active hip control. Use the hands lightly and keep the chest lifted.", 3],
  ["ninety-ninety-hip-switch", "safety", "Reduce range or use more hand support if the hips or knees pinch.", 4],
  ["ankle-dorsiflexion-rock", "setup", "Stand in a split stance facing a wall or rack with the front foot flat and toes pointing forward.", 1],
  ["ankle-dorsiflexion-rock", "execution", "Drive the front knee toward the toes while the heel stays down, then rock back and repeat smoothly.", 2],
  ["ankle-dorsiflexion-rock", "common_error", "Letting the arch collapse inward creates the appearance of range without true ankle control. Keep the knee tracking over the middle toes.", 3],
  ["ankle-dorsiflexion-rock", "safety", "Stay in a pain-free range and avoid forcing through pinching at the front of the ankle.", 4],
  ["deep-squat-pry", "setup", "Stand with feet about squat width and lower into the deepest comfortable squat while keeping the heels grounded if possible.", 1],
  ["deep-squat-pry", "execution", "Use the elbows or hands to gently shift side to side and open the hips while maintaining relaxed breathing.", 2],
  ["deep-squat-pry", "common_error", "Forcing depth by rounding hard through the low back or lifting the heels changes the target. Use a shallower range or support.", 3],
  ["deep-squat-pry", "safety", "Hold a rack or reduce depth for clients with knee, hip, or ankle symptoms.", 4],
];

export const RELATIONS: Array<[string, string, ExerciseRelationType, string]> = [
  ["bodyweight-standing-calf-raise", "single-leg-standing-calf-raise", "regression", "The two-leg bodyweight raise is the simpler calf-strength entry point before unilateral loading."],
  ["single-leg-standing-calf-raise", "bodyweight-standing-calf-raise", "progression", "Single-leg loading increases calf demand and balance cost compared with the two-leg bodyweight raise."],
  ["bodyweight-standing-calf-raise", "dumbbell-standing-calf-raise", "regression", "Bodyweight calf raises remove external load while preserving the same standing ankle action."],
  ["dumbbell-standing-calf-raise", "bodyweight-standing-calf-raise", "progression", "Dumbbells progress the same standing calf pattern when bodyweight volume is no longer enough."],
  ["standing-calf-raise-machine", "leg-press-calf-raise", "substitute", "Both provide loaded straight-knee calf work with machine stability; choose based on equipment and comfort."],
  ["leg-press-calf-raise", "standing-calf-raise-machine", "substitute", "Both provide loaded straight-knee calf work with machine stability; leg press setup reduces balance demand."],
  ["seated-calf-raise", "standing-calf-raise-machine", "substitute", "Both train plantarflexion with machine loading; seated positioning biases bent-knee calf work."],
  ["standing-calf-raise-machine", "seated-calf-raise", "substitute", "Both train plantarflexion with machine loading; standing positioning biases straight-knee calf work."],
  ["seated-calf-raise", "standing-calf-raise-machine", "lower_joint_stress", "Seated calf raise reduces balance and axial loading compared with a standing machine setup."],
  ["standing-calf-raise-machine", "seated-calf-raise", "higher_joint_stress", "Standing calf raise carries more axial and balance demand than the seated machine variation."],

  ["treadmill-walk", "treadmill-run", "regression", "Walking is the lower-impact gait option before progressing to running volume or speed."],
  ["treadmill-run", "treadmill-walk", "progression", "Running progresses treadmill gait with higher impact, cadence, and cardiovascular demand."],
  ["treadmill-walk", "incline-treadmill-walk", "regression", "Flat walking removes the incline demand when calves, Achilles, or conditioning are not ready."],
  ["incline-treadmill-walk", "treadmill-walk", "progression", "Incline walking increases posterior-chain and cardiovascular demand without requiring running."],
  ["elliptical", "treadmill-run", "lower_joint_stress", "Elliptical conditioning preserves upright cardio work with less impact than treadmill running."],
  ["treadmill-run", "elliptical", "higher_joint_stress", "Running carries higher impact and ankle/knee stress than elliptical conditioning."],
  ["stationary-bike", "treadmill-run", "lower_joint_stress", "Stationary cycling reduces impact and balance demand while maintaining cardiovascular stimulus."],
  ["treadmill-run", "stationary-bike", "higher_joint_stress", "Treadmill running has higher impact and standing balance demand than stationary cycling."],
  ["recumbent-bike", "stationary-bike", "lower_joint_stress", "Recumbent cycling provides back support and the lowest balance demand among bike options."],
  ["stationary-bike", "recumbent-bike", "higher_joint_stress", "Upright cycling has more trunk and hip-position demand than recumbent cycling."],
  ["rowing-machine", "stationary-bike", "substitute", "Both are seated machine cardio options; rowing adds more upper-back and sequencing demand."],
  ["stationary-bike", "rowing-machine", "substitute", "Both are seated machine cardio options; bike work is simpler when rowing technique is a limiter."],
  ["stair-climber", "incline-treadmill-walk", "substitute", "Both are upright low-skill cardio choices with elevated lower-body demand."],
  ["incline-treadmill-walk", "stair-climber", "substitute", "Both are upright low-skill cardio choices with elevated lower-body demand."],

  ["band-shoulder-external-rotation-mobility", "wall-slide", "substitute", "Both are low-load shoulder-prep drills; use external rotation when cuff control is the priority."],
  ["wall-slide", "band-shoulder-external-rotation-mobility", "substitute", "Both are low-load shoulder-prep drills; use wall slides when overhead position is the priority."],
  ["thoracic-extension-on-foam-roller", "open-book-thoracic-rotation", "substitute", "Both address thoracic mobility; choose extension or rotation based on the session need."],
  ["open-book-thoracic-rotation", "thoracic-extension-on-foam-roller", "substitute", "Both address thoracic mobility; choose rotation or extension based on the session need."],
  ["ankle-dorsiflexion-rock", "deep-squat-pry", "regression", "Ankle rocks isolate one limiting component before combining ankle, hip, and squat-depth demands."],
  ["deep-squat-pry", "ankle-dorsiflexion-rock", "progression", "Deep squat pry progresses ankle mobility into an integrated squat-position drill."],
];
