// ─────────────────────────────────────────────────────────────
// Kynovant — Exercise Library Seed Data 010: AI Vocabulary Coverage
// ─────────────────────────────────────────────────────────────

import type {
  EquipmentRequirement,
  ExerciseCueType,
  ExerciseDef,
  ExerciseRelationType,
  MuscleGroup,
  MuscleRole,
} from "./_shared";

export const WARMUP_MOBILITY_SLUGS = [
  "arm-circles",
  "cat-cow-stretch",
  "forward-leg-swing",
  "lateral-leg-swing",
  "bodyweight-good-morning",
] as const;

export const NEW_STRENGTH_SLUGS = [
  "band-chest-fly",
  "bench-dip",
  "dumbbell-front-raise",
  "cable-front-raise",
  "barbell-upright-row",
  "cable-upright-row",
] as const;

const warmupPrescription = {
  sets: 1,
  repsMin: 8,
  repsMax: 12,
  targetRpe: 2,
  restSeconds: 15,
  substitutionPolicy: "flexible",
};

const strengthPrescription = {
  sets: 2,
  repsMin: 10,
  repsMax: 15,
  tempo: "2111",
  targetRpe: 7,
  restSeconds: 60,
  substitutionPolicy: "flexible",
};

export const EXERCISES = [
  {
    slug: "arm-circles",
    name: "Arm Circles",
    alternateNames: ["Arm Circle", "Shoulder Circles", "Shoulder Circle"],
    movementPattern: "shoulder_abduction",
    classification: "mobility",
    resistanceType: "bodyweight",
    difficulty: "beginner",
    isMobility: true,
    defaultBodyPosition: "standing",
    fatigueCost: 1,
    technicalComplexity: 1,
    stabilityDemand: 1,
    jointStressShoulder: 1,
    jointStressElbow: 0,
    lengthenedBias: 0,
    shortenedBias: 0,
    stretchMediatedPotential: 0,
    defaultPrescription: warmupPrescription,
  },
  {
    slug: "cat-cow-stretch",
    name: "Cat-Cow Stretch",
    alternateNames: ["Cat Cow Stretch", "Cat Cow", "Cat-Cow"],
    movementPattern: "rotation",
    classification: "mobility",
    resistanceType: "bodyweight",
    difficulty: "beginner",
    isMobility: true,
    defaultBodyPosition: "quadruped",
    fatigueCost: 1,
    technicalComplexity: 1,
    stabilityDemand: 2,
    jointStressSpine: 1,
    jointStressWrist: 1,
    jointStressHip: 1,
    lengthenedBias: 0,
    shortenedBias: 0,
    stretchMediatedPotential: 0,
    defaultPrescription: warmupPrescription,
  },
  {
    slug: "forward-leg-swing",
    name: "Forward Leg Swing",
    alternateNames: ["Front-to-Back Leg Swing", "Front Back Leg Swing"],
    movementPattern: "hip_flexion",
    classification: "mobility",
    resistanceType: "bodyweight",
    difficulty: "beginner",
    unilateral: true,
    alternating: true,
    isMobility: true,
    defaultBodyPosition: "standing",
    fatigueCost: 1,
    technicalComplexity: 1,
    stabilityDemand: 3,
    jointStressHip: 2,
    jointStressKnee: 1,
    jointStressAnkle: 1,
    lengthenedBias: 0,
    shortenedBias: 0,
    stretchMediatedPotential: 0,
    defaultPrescription: warmupPrescription,
  },
  {
    slug: "lateral-leg-swing",
    name: "Lateral Leg Swing",
    alternateNames: ["Side-to-Side Leg Swing", "Side Leg Swing"],
    movementPattern: "hip_flexion",
    classification: "mobility",
    resistanceType: "bodyweight",
    difficulty: "beginner",
    unilateral: true,
    alternating: true,
    isMobility: true,
    defaultBodyPosition: "standing",
    fatigueCost: 1,
    technicalComplexity: 1,
    stabilityDemand: 3,
    jointStressHip: 2,
    jointStressKnee: 1,
    jointStressAnkle: 1,
    lengthenedBias: 0,
    shortenedBias: 0,
    stretchMediatedPotential: 0,
    defaultPrescription: warmupPrescription,
  },
  {
    slug: "bodyweight-good-morning",
    name: "Bodyweight Good Morning",
    alternateNames: ["Bodyweight Good Mornings", "Hip Hinge Drill"],
    movementPattern: "hip_hinge",
    classification: "mobility",
    resistanceType: "bodyweight",
    difficulty: "beginner",
    isMobility: true,
    defaultBodyPosition: "standing",
    fatigueCost: 1,
    technicalComplexity: 2,
    stabilityDemand: 2,
    jointStressSpine: 1,
    jointStressHip: 2,
    jointStressKnee: 1,
    lengthenedBias: 0,
    shortenedBias: 0,
    stretchMediatedPotential: 0,
    defaultPrescription: warmupPrescription,
  },
  {
    slug: "band-chest-fly",
    name: "Band Chest Fly",
    alternateNames: ["Band Chest Flye", "Band Chest Flyes", "Resistance Band Chest Fly"],
    movementPattern: "push_horizontal",
    classification: "isolation",
    resistanceType: "band",
    difficulty: "beginner",
    defaultBodyPosition: "standing",
    fatigueCost: 2,
    technicalComplexity: 2,
    stabilityDemand: 3,
    jointStressShoulder: 3,
    jointStressElbow: 1,
    jointStressSpine: 1,
    lengthenedBias: 4,
    shortenedBias: 7,
    stretchMediatedPotential: 3,
    defaultPrescription: strengthPrescription,
  },
  {
    slug: "bench-dip",
    name: "Bench Dip",
    alternateNames: ["Tricep Dip", "Tricep Dips", "Triceps Dip", "Triceps Dips"],
    movementPattern: "elbow_extension",
    classification: "compound",
    resistanceType: "bodyweight",
    difficulty: "beginner",
    defaultBodyPosition: "seated",
    fatigueCost: 4,
    technicalComplexity: 3,
    stabilityDemand: 3,
    jointStressShoulder: 6,
    jointStressElbow: 4,
    jointStressWrist: 3,
    jointStressSpine: 1,
    lengthenedBias: 5,
    shortenedBias: 5,
    stretchMediatedPotential: 3,
    defaultPrescription: { ...strengthPrescription, repsMin: 8, repsMax: 12, substitutionPolicy: "coach_review" },
  },
  {
    slug: "dumbbell-front-raise",
    name: "Dumbbell Front Raise",
    alternateNames: ["Dumbbell Front Raises"],
    movementPattern: "push_vertical",
    classification: "isolation",
    resistanceType: "dumbbell",
    difficulty: "beginner",
    defaultBodyPosition: "standing",
    fatigueCost: 2,
    technicalComplexity: 2,
    stabilityDemand: 3,
    jointStressShoulder: 4,
    jointStressElbow: 1,
    jointStressWrist: 2,
    lengthenedBias: 1,
    shortenedBias: 7,
    stretchMediatedPotential: 1,
    defaultPrescription: strengthPrescription,
  },
  {
    slug: "cable-front-raise",
    name: "Cable Front Raise",
    alternateNames: ["Cable Front Raises"],
    movementPattern: "push_vertical",
    classification: "isolation",
    resistanceType: "cable",
    difficulty: "beginner",
    unilateral: true,
    defaultBodyPosition: "standing",
    fatigueCost: 2,
    technicalComplexity: 3,
    stabilityDemand: 4,
    jointStressShoulder: 4,
    jointStressElbow: 1,
    jointStressWrist: 2,
    lengthenedBias: 4,
    shortenedBias: 6,
    stretchMediatedPotential: 3,
    defaultPrescription: strengthPrescription,
  },
  {
    slug: "barbell-upright-row",
    name: "Barbell Upright Row",
    alternateNames: ["Barbell Upright Rows"],
    movementPattern: "shoulder_abduction",
    classification: "compound",
    resistanceType: "barbell",
    difficulty: "intermediate",
    defaultBodyPosition: "standing",
    fatigueCost: 4,
    technicalComplexity: 4,
    stabilityDemand: 4,
    jointStressShoulder: 7,
    jointStressElbow: 3,
    jointStressWrist: 4,
    jointStressSpine: 2,
    lengthenedBias: 2,
    shortenedBias: 6,
    stretchMediatedPotential: 1,
    defaultPrescription: { ...strengthPrescription, repsMin: 8, repsMax: 12, substitutionPolicy: "coach_review" },
  },
  {
    slug: "cable-upright-row",
    name: "Cable Upright Row",
    alternateNames: ["Cable Upright Rows"],
    movementPattern: "shoulder_abduction",
    classification: "compound",
    resistanceType: "cable",
    difficulty: "intermediate",
    defaultBodyPosition: "standing",
    fatigueCost: 3,
    technicalComplexity: 3,
    stabilityDemand: 3,
    jointStressShoulder: 6,
    jointStressElbow: 3,
    jointStressWrist: 2,
    jointStressSpine: 1,
    lengthenedBias: 3,
    shortenedBias: 6,
    stretchMediatedPotential: 2,
    defaultPrescription: { ...strengthPrescription, repsMin: 8, repsMax: 12, substitutionPolicy: "coach_review" },
  },
] as const satisfies readonly ExerciseDef[];

export const MUSCLES: Array<[string, MuscleGroup, MuscleRole]> = [
  ["arm-circles", "lateral_deltoid", "primary"],
  ["arm-circles", "front_deltoid", "secondary"],
  ["arm-circles", "rear_deltoid", "secondary"],
  ["cat-cow-stretch", "spinal_erectors", "primary"],
  ["cat-cow-stretch", "rectus_abdominis", "secondary"],
  ["cat-cow-stretch", "transverse_abdominis", "stabilizer"],
  ["forward-leg-swing", "hip_flexors", "primary"],
  ["forward-leg-swing", "hamstrings", "secondary"],
  ["forward-leg-swing", "glutes", "stabilizer"],
  ["lateral-leg-swing", "adductors", "primary"],
  ["lateral-leg-swing", "abductors", "secondary"],
  ["lateral-leg-swing", "glutes", "stabilizer"],
  ["bodyweight-good-morning", "hamstrings", "primary"],
  ["bodyweight-good-morning", "glutes", "secondary"],
  ["bodyweight-good-morning", "spinal_erectors", "stabilizer"],
  ["band-chest-fly", "chest", "primary"],
  ["band-chest-fly", "front_deltoid", "secondary"],
  ["bench-dip", "triceps", "primary"],
  ["bench-dip", "chest", "secondary"],
  ["bench-dip", "front_deltoid", "secondary"],
  ["dumbbell-front-raise", "front_deltoid", "primary"],
  ["dumbbell-front-raise", "lateral_deltoid", "secondary"],
  ["dumbbell-front-raise", "trapezius", "stabilizer"],
  ["cable-front-raise", "front_deltoid", "primary"],
  ["cable-front-raise", "lateral_deltoid", "secondary"],
  ["cable-front-raise", "trapezius", "stabilizer"],
  ["barbell-upright-row", "lateral_deltoid", "primary"],
  ["barbell-upright-row", "trapezius", "secondary"],
  ["barbell-upright-row", "front_deltoid", "secondary"],
  ["barbell-upright-row", "forearms", "stabilizer"],
  ["cable-upright-row", "lateral_deltoid", "primary"],
  ["cable-upright-row", "trapezius", "secondary"],
  ["cable-upright-row", "front_deltoid", "secondary"],
  ["cable-upright-row", "forearms", "stabilizer"],
];

export const EXERCISE_EQUIPMENT: Array<[string, string, EquipmentRequirement]> = [
  ["band-chest-fly", "resistance-band", "required"],
  ["bench-dip", "flat-bench", "required"],
  ["dumbbell-front-raise", "dumbbells", "required"],
  ["cable-front-raise", "cable-station", "required"],
  ["barbell-upright-row", "barbell", "required"],
  ["cable-upright-row", "cable-station", "required"],
];

export const CUES: Array<[string, ExerciseCueType, string, number]> = [
  ["arm-circles", "setup", "Stand tall with arms reaching out to the sides at shoulder height and palms relaxed.", 1],
  ["arm-circles", "execution", "Make small controlled circles from the shoulder, gradually increasing range only while the ribs stay down and the neck stays relaxed.", 2],
  ["arm-circles", "common_error", "Shrugging the shoulders toward the ears turns the drill into trap tension instead of shoulder preparation.", 3],
  ["arm-circles", "safety", "Use pain-free range only and reduce circle size if the shoulder pinches.", 4],
  ["cat-cow-stretch", "setup", "Start on hands and knees with hands under shoulders and knees under hips.", 1],
  ["cat-cow-stretch", "execution", "Move slowly between rounding the upper and lower back and extending through the spine, matching the motion to relaxed breathing.", 2],
  ["cat-cow-stretch", "common_error", "Rushing through the drill without segmental spine motion turns it into neck nodding. Move one controlled breath at a time.", 3],
  ["cat-cow-stretch", "safety", "Keep pressure comfortable through the wrists and avoid forcing end range if symptoms travel into the back or hips.", 4],
  ["forward-leg-swing", "setup", "Stand tall near a rack or wall for light balance support with one leg free to swing.", 1],
  ["forward-leg-swing", "execution", "Swing the leg forward and backward under control, letting range build gradually without arching the low back.", 2],
  ["forward-leg-swing", "common_error", "Leaning the torso back to kick higher creates false hip range. Stay tall and keep the pelvis quiet.", 3],
  ["forward-leg-swing", "safety", "Use a smaller range for hamstring or hip-flexor sensitivity and stop if the hip pinches.", 4],
  ["lateral-leg-swing", "setup", "Stand facing a rack or wall with both hands lightly supported and one leg free to move across the body.", 1],
  ["lateral-leg-swing", "execution", "Swing the leg side to side across a comfortable range while keeping the trunk tall and the planted foot stable.", 2],
  ["lateral-leg-swing", "common_error", "Rotating the whole torso turns the drill into momentum. Keep the chest mostly square and move through the hip.", 3],
  ["lateral-leg-swing", "safety", "Stay below any pinching range at the front or side of the hip.", 4],
  ["bodyweight-good-morning", "setup", "Stand with feet hip-width, hands across the chest or behind the head, and knees softly unlocked.", 1],
  ["bodyweight-good-morning", "execution", "Push the hips back while keeping the spine long, then drive the hips forward to stand tall without turning it into a squat.", 2],
  ["bodyweight-good-morning", "common_error", "Bending the knees too much hides the hinge pattern. Keep the knees soft but let the hips do the motion.", 3],
  ["bodyweight-good-morning", "safety", "Use this as a low-load patterning drill; stop before any low-back rounding or discomfort.", 4],
  ["band-chest-fly", "setup", "Anchor a band behind the body at chest height and step forward until light tension is present with arms open and elbows softly bent.", 1],
  ["band-chest-fly", "execution", "Sweep the hands together in front of the chest while keeping the elbow bend fixed, then return slowly into a controlled stretch.", 2],
  ["band-chest-fly", "common_error", "Pressing with the triceps instead of sweeping from the shoulders changes the drill into a press. Keep the arms in a wide arc.", 3],
  ["band-chest-fly", "safety", "Use light band tension and avoid forcing a deep shoulder stretch behind the torso.", 4],
  ["bench-dip", "setup", "Sit on the edge of a stable bench with hands beside the hips, feet planted, and shoulders pulled slightly back and down.", 1],
  ["bench-dip", "execution", "Lower by bending the elbows until the shoulders remain comfortable, then press through the hands to extend the elbows.", 2],
  ["bench-dip", "common_error", "Dropping too deep with shoulders rolling forward places high stress on the front of the shoulder. Keep range conservative.", 3],
  ["bench-dip", "safety", "Avoid this exercise for clients with anterior shoulder pain; substitute a cable or band pushdown instead.", 4],
  ["dumbbell-front-raise", "setup", "Stand tall holding dumbbells in front of the thighs with palms facing the body and ribs stacked over the pelvis.", 1],
  ["dumbbell-front-raise", "execution", "Raise the dumbbells forward to about shoulder height without leaning back, then lower under control.", 2],
  ["dumbbell-front-raise", "common_error", "Swinging from the hips lets momentum replace delt tension. Reduce the load and pause between reps.", 3],
  ["dumbbell-front-raise", "safety", "Stop short of shoulder pinching and keep loads modest; front delts are usually already trained by pressing volume.", 4],
  ["cable-front-raise", "setup", "Stand facing away from a low cable with the handle held in front of the thighs and the cable running between the legs or beside the body.", 1],
  ["cable-front-raise", "execution", "Raise the handle forward to shoulder height against steady cable tension, then return slowly without twisting.", 2],
  ["cable-front-raise", "common_error", "Letting the torso rotate or lean back changes the line of pull. Square the hips and reduce the load.", 3],
  ["cable-front-raise", "safety", "Use a range that stays clear of shoulder impingement and avoid aggressive bottom-position stretch.", 4],
  ["barbell-upright-row", "setup", "Stand tall with a barbell held in front of the thighs using a grip that allows the wrists to stay comfortable.", 1],
  ["barbell-upright-row", "execution", "Pull the bar upward toward the lower chest by driving elbows out and up, stopping before the shoulders pinch or elbows rise excessively high.", 2],
  ["barbell-upright-row", "common_error", "Pulling high toward the chin with internally rotated shoulders increases impingement risk. Limit range and keep the bar close.", 3],
  ["barbell-upright-row", "safety", "Use coach review for clients with shoulder impingement history; cable or lateral-raise options are often better tolerated.", 4],
  ["cable-upright-row", "setup", "Attach a straight or EZ handle to a low cable and stand tall with the handle in front of the thighs.", 1],
  ["cable-upright-row", "execution", "Pull elbows out and up to bring the handle toward the lower chest, then lower slowly under constant cable tension.", 2],
  ["cable-upright-row", "common_error", "Letting the wrists bend sharply or pulling above comfortable shoulder range adds joint stress without improving stimulus.", 3],
  ["cable-upright-row", "safety", "Keep range conservative and stop immediately if the front or top of the shoulder pinches.", 4],
];

export const INTRA_FILE_RELATIONS: Array<[string, string, ExerciseRelationType, string]> = [
  ["forward-leg-swing", "lateral-leg-swing", "same_pattern", "Both are dynamic hip warm-up drills; front-to-back and lateral planes should be selected by session need."],
  ["lateral-leg-swing", "forward-leg-swing", "same_pattern", "Both are dynamic hip warm-up drills; lateral and front-to-back planes should be selected by session need."],
  ["dumbbell-front-raise", "cable-front-raise", "same_pattern", "Both train shoulder flexion/front-delt emphasis; cable loading keeps more tension near the bottom."],
  ["cable-front-raise", "dumbbell-front-raise", "same_pattern", "Both train shoulder flexion/front-delt emphasis; dumbbells are simpler when cable setup is unavailable."],
  ["barbell-upright-row", "cable-upright-row", "same_pattern", "Both train upright-row mechanics; the cable path is usually easier to adjust for shoulder comfort."],
  ["cable-upright-row", "barbell-upright-row", "same_pattern", "Both train upright-row mechanics; the barbell path is less adjustable and generally higher stress."],
  ["cable-upright-row", "barbell-upright-row", "lower_joint_stress", "Cable loading permits a narrower range and smoother resistance curve than the fixed barbell path."],
  ["barbell-upright-row", "cable-upright-row", "higher_joint_stress", "The barbell path generally creates higher wrist and shoulder constraint than a cable upright row."],
];

export type AiVocabularyRelation = {
  sourceSlug: string;
  targetSlug: string;
  relationType: ExerciseRelationType;
  substitutionPolicy: "strict" | "flexible" | "coach_review" | "no_substitute";
  suitabilityScore: number;
  notes: string;
};

export const CROSS_FILE_RELATIONS = [
  {
    sourceSlug: "band-chest-fly",
    targetSlug: "cable-chest-fly",
    relationType: "substitute",
    substitutionPolicy: "flexible",
    suitabilityScore: 82,
    notes: "Band chest fly is the low-equipment substitute for the standard cable chest fly pattern.",
  },
  {
    sourceSlug: "cable-chest-fly",
    targetSlug: "band-chest-fly",
    relationType: "substitute",
    substitutionPolicy: "flexible",
    suitabilityScore: 82,
    notes: "Cable chest fly substitutes for band fly when a cable station is available and load needs to be progressed precisely.",
  },
  {
    sourceSlug: "bench-dip",
    targetSlug: "cable-triceps-pushdown-straight-bar",
    relationType: "higher_joint_stress",
    substitutionPolicy: "coach_review",
    suitabilityScore: 78,
    notes: "Bench dips load the shoulder in extension and are higher stress than a cable pushdown.",
  },
  {
    sourceSlug: "cable-triceps-pushdown-straight-bar",
    targetSlug: "bench-dip",
    relationType: "lower_joint_stress",
    substitutionPolicy: "flexible",
    suitabilityScore: 78,
    notes: "Cable pushdown is the lower-shoulder-stress substitution when a generated triceps dip is not appropriate.",
  },
  {
    sourceSlug: "bodyweight-good-morning",
    targetSlug: "good-morning",
    relationType: "regression",
    substitutionPolicy: "flexible",
    suitabilityScore: 86,
    notes: "Bodyweight good morning is the warm-up and patterning regression before loaded barbell good mornings.",
  },
  {
    sourceSlug: "good-morning",
    targetSlug: "bodyweight-good-morning",
    relationType: "progression",
    substitutionPolicy: "coach_review",
    suitabilityScore: 86,
    notes: "Loaded good morning progresses the same hinge pattern with much higher spine and hamstring loading.",
  },
] as const satisfies readonly AiVocabularyRelation[];
